package omnivoice

import "encoding/json"

// Server message types.
const (
	TypeSetupComplete  = "setupComplete"
	TypeServerContent  = "serverContent"
	TypeToolCall       = "toolCall"
	TypeToolCallCancel = "toolCallCancellation"
)

// ServerMessage represents a message received from the server.
type ServerMessage interface {
	GetType() string
}

// SetupComplete is sent when the session setup is complete.
type SetupComplete struct {
	Type string `json:"-"`
}

func (s *SetupComplete) GetType() string { return TypeSetupComplete }

// ServerContent contains content generated by the model.
type ServerContent struct {
	Type          string         `json:"-"`
	ModelTurn     *ModelTurn     `json:"modelTurn,omitempty"`
	TurnComplete  bool           `json:"turnComplete,omitempty"`
	Interrupted   bool           `json:"interrupted,omitempty"`
	GroundingMeta *GroundingMeta `json:"groundingMetadata,omitempty"`
}

func (s *ServerContent) GetType() string { return TypeServerContent }

// ModelTurn represents a turn from the model.
type ModelTurn struct {
	Parts []Part `json:"parts"`
}

// Part represents a content part.
type Part struct {
	Text       string      `json:"text,omitempty"`
	InlineData *InlineData `json:"inlineData,omitempty"`
	ExecCode   *ExecCode   `json:"executableCode,omitempty"`
	CodeResult *CodeResult `json:"codeExecutionResult,omitempty"`
}

// InlineData contains inline binary data.
type InlineData struct {
	MimeType string `json:"mimeType"`
	Data     string `json:"data"` // base64 encoded
}

// ExecCode contains executable code.
type ExecCode struct {
	Language string `json:"language"`
	Code     string `json:"code"`
}

// CodeResult contains code execution result.
type CodeResult struct {
	Outcome string `json:"outcome"`
	Output  string `json:"output"`
}

// GroundingMeta contains grounding metadata.
type GroundingMeta struct {
	SearchResults []SearchResult `json:"searchEntryPoint,omitempty"`
	WebSearch     *WebSearch     `json:"webSearchQueries,omitempty"`
}

// SearchResult represents a search result.
type SearchResult struct {
	RenderedContent string `json:"renderedContent"`
}

// WebSearch contains web search queries.
type WebSearch struct {
	Queries []string `json:"queries"`
}

// ToolCall represents a function call from the model.
type ToolCall struct {
	Type          string         `json:"-"`
	FunctionCalls []FunctionCall `json:"functionCalls"`
}

func (t *ToolCall) GetType() string { return TypeToolCall }

// FunctionCall represents a single function call.
type FunctionCall struct {
	ID   string          `json:"id"`
	Name string          `json:"name"`
	Args json.RawMessage `json:"args"`
}

// ToolCallCancel is sent when a tool call is cancelled.
type ToolCallCancel struct {
	Type string   `json:"-"`
	IDs  []string `json:"ids"`
}

func (t *ToolCallCancel) GetType() string { return TypeToolCallCancel }

// Client message types.

// SetupMessage is sent to configure the session.
type SetupMessage struct {
	Setup *SetupConfig `json:"setup"`
}

// SetupConfig configures the session.
type SetupConfig struct {
	Model             string            `json:"model"`
	GenerationConfig  *GenerationConfig `json:"generationConfig,omitempty"`
	SystemInstruction *Content          `json:"systemInstruction,omitempty"`
	Tools             []ToolDef         `json:"tools,omitempty"`
}

// GenerationConfig configures generation parameters.
type GenerationConfig struct {
	ResponseModalities []string      `json:"responseModalities,omitempty"`
	SpeechConfig       *SpeechConfig `json:"speechConfig,omitempty"`
	Temperature        float64       `json:"temperature,omitempty"`
	TopP               float64       `json:"topP,omitempty"`
	TopK               int           `json:"topK,omitempty"`
	MaxOutputTokens    int           `json:"maxOutputTokens,omitempty"`
	CandidateCount     int           `json:"candidateCount,omitempty"`
}

// SpeechConfig configures speech output.
type SpeechConfig struct {
	VoiceConfig *VoiceConfig `json:"voiceConfig,omitempty"`
}

// VoiceConfig configures the voice.
type VoiceConfig struct {
	PrebuiltVoiceConfig *PrebuiltVoiceConfig `json:"prebuiltVoiceConfig,omitempty"`
}

// PrebuiltVoiceConfig configures a prebuilt voice.
type PrebuiltVoiceConfig struct {
	VoiceName string `json:"voiceName"`
}

// Content represents content with parts.
type Content struct {
	Parts []Part `json:"parts"`
	Role  string `json:"role,omitempty"`
}

// ToolDef defines a tool.
type ToolDef struct {
	FunctionDeclarations []FunctionDeclaration `json:"functionDeclarations,omitempty"`
	GoogleSearch         *GoogleSearchConfig   `json:"googleSearch,omitempty"`
	CodeExecution        *CodeExecutionConfig  `json:"codeExecution,omitempty"`
}

// FunctionDeclaration declares a function.
type FunctionDeclaration struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Parameters  json.RawMessage `json:"parameters,omitempty"`
}

// GoogleSearchConfig enables Google Search.
type GoogleSearchConfig struct{}

// CodeExecutionConfig enables code execution.
type CodeExecutionConfig struct{}

// RealtimeInput sends realtime audio/video input.
type RealtimeInput struct {
	RealtimeInput *RealtimeInputData `json:"realtimeInput"`
}

// RealtimeInputData contains realtime input data.
type RealtimeInputData struct {
	MediaChunks []MediaChunk `json:"mediaChunks"`
}

// MediaChunk represents a chunk of media data.
type MediaChunk struct {
	MimeType string `json:"mimeType"`
	Data     string `json:"data"` // base64 encoded
}

// ClientContent sends text content.
type ClientContent struct {
	ClientContent *ClientContentData `json:"clientContent"`
}

// ClientContentData contains client content.
type ClientContentData struct {
	Turns        []Content `json:"turns,omitempty"`
	TurnComplete bool      `json:"turnComplete,omitempty"`
}

// ToolResponse sends function call results.
type ToolResponse struct {
	ToolResponse *ToolResponseData `json:"toolResponse"`
}

// ToolResponseData contains tool response data.
type ToolResponseData struct {
	FunctionResponses []FunctionResponse `json:"functionResponses"`
}

// FunctionResponse provides a function call result.
type FunctionResponse struct {
	ID       string          `json:"id"`
	Name     string          `json:"name"`
	Response json.RawMessage `json:"response"`
}

// rawServerMessage is used for initial parsing.
type rawServerMessage struct {
	SetupComplete        *SetupComplete  `json:"setupComplete,omitempty"`
	ServerContent        *ServerContent  `json:"serverContent,omitempty"`
	ToolCall             *ToolCall       `json:"toolCall,omitempty"`
	ToolCallCancellation *ToolCallCancel `json:"toolCallCancellation,omitempty"`
}

// parseServerMessage parses a raw JSON message into a typed event.
func parseServerMessage(data []byte) (ServerMessage, error) {
	var raw rawServerMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	if raw.SetupComplete != nil {
		raw.SetupComplete.Type = TypeSetupComplete
		return raw.SetupComplete, nil
	}
	if raw.ServerContent != nil {
		raw.ServerContent.Type = TypeServerContent
		return raw.ServerContent, nil
	}
	if raw.ToolCall != nil {
		raw.ToolCall.Type = TypeToolCall
		return raw.ToolCall, nil
	}
	if raw.ToolCallCancellation != nil {
		raw.ToolCallCancellation.Type = TypeToolCallCancel
		return raw.ToolCallCancellation, nil
	}

	return nil, nil
}
